### ISSUE TITLE
Spotify to Plex via docker

### ISSUE THREAD

**Issue by Drazzilb08** [XDGFX/ultrasonics#33]
So I've installed ultrasonics via docker on my unraid server. I've set everything up, ultrasonics connects to my Spotify account, and connects to my Plex server.
When I run the applet I receive this error:
```
plugins - DEBUG - Running plugin plex v0.1 (plugins.py:158)
today at 6:50:18 PM 2021-10-21 01:50:18,379 - 🎧 plex - INFO - Requesting playlists from endpoint: http://192.168.1.200:32400/playlists/?X-Plex-Token=*********** (up_plex.py:179)
today at 6:50:18 PM 2021-10-21 01:50:18,383 - 🎧 plex - INFO - Found 1 playlists. (up_plex.py:195)
today at 6:50:18 PM 2021-10-21 01:50:18,383 - 🎧 plex - INFO - Creating temporary playlists to send to Plex. (up_plex.py:239)
today at 6:50:18 PM 2021-10-21 01:50:18,399 - 🎧 plex - INFO - Updating playlist: EDM Bangers (up_plex.py:243)
today at 6:50:18 PM 2021-10-21 01:50:18,412 - 🎧 plex - DEBUG - <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html> (up_plex.py:298)
```
which duplicates across all my Spotify playlists.

I've tested my plex URL + the token and I get a normal response

The run shows as successful but it is not, obviously
```
Today at 6:50:19 PM 2021-10-21 01:50:19,474 - plugins - INFO - Applet 7bbc3df8-3203-11ec-a41c-0242ac11000b completed successfully in 0:00:14.873865 (plugins.py:296)
```
My docker setup:
```yml
services:
  ultrasonics:
    command:
      - app.py
    container_name: ultrasonics
    entrypoint:
      - python
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
      - HOST_OS=Unraid
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
      - PYTHON_VERSION=3.8.5
      - PYTHON_PIP_VERSION=20.2.3
      - PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py
      - PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c
    hostname: 9dd093140e87
    image: xdgfx/ultrasonics:latest
    ipc: private
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 50m
    networks:
      - external
    ports:
      - 5000:5000/tcp
    volumes:
      - /mnt/user/appdata/ultrasonics:/config:rw
      - /mnt/user/appdata/ultrasonics/plugins:/plugins:rw
      - /mnt/user/data/:/data:rw
    working_dir: /
networks:
  external:
    external: true
```
I really want to use this app as it's exactly what I've been looking for. Just got this one issue.
